language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

  fast_finish: true

cache: cargo

branches:
  - master

addons:
  apt:
    update: true
    packages:
      - libxtst-dev
