language: rust

addons:
  apt:
    update: true
    packages:
      - libxtst-dev
      - xdotool
  
before_install:
  - if [ $TRAVIS_RUST_VERSION == nightly ]; then rustup component add clippy-preview ; fi

branches:
  - master

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

  fast_finish: true

script:
  - cargo build --verbose
  - cargo test --verbose
  - if [ $TRAVIS_RUST_VERSION == nightly ]; then cargo clippy ; fi

cache: cargo

