language: rust
sudo: required

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

  fast_finish: true

cache: cargo

branches:
  - master

before_install:
  - sudo apt-get install -y libxtst-dev
addons:
  apt:
    update: true